# ─────────────────────────────────────────────────────────────────
# keymaps/vial/rules.mk — keymap level
# Generated by QMK/Vial Wizard v5.6 on 2026-08-29
# ─────────────────────────────────────────────────────────────────
#
# VIAL_ENABLE must live here and only here — not at the keyboard level.
# This is per the official Vial porting documentation.
# Reference: https://get.vial.today/docs/porting-to-vial.html
#
VIAL_ENABLE = yes
ENCODER_ENABLE = yes

DEBOUNCE_TYPE = sym_defer_g







